# Generated by Django 4.2.6 on 2023-10-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(verbose_name='date_created')),
                ('accounting_period', models.CharField(max_length=400)),
                ('scope_1', models.IntegerField(null=True)),
                ('scope_2', models.IntegerField(null=True)),
                ('scope_3', models.IntegerField(null=True)),
            ],
        ),
    ]
